name: ci

on:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: make install
      - name: Run phpunit
        run: make test

  phpunit_en:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: cd en && make install
      - name: Run phpunit
        run: cd en && make test